
import Head from 'next/head';
import { Header } from '../components/Header';
import Homepage from '../components/Homepage';
import AboutPage from '../components/AboutPage';
import ServicePage from '../components/ServicePage';
import ContactForm from '../components/ContactForm';


export default function Home() {
  return (
    <div className="" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div className="  overflow-hidden bg-cover bg-center bg-[url('https://images.unsplash.com/photo-1547949003-9792a18a2601?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80')]" >
      <Header />
   <Homepage/>

      </div>
      <ServicePage/>
      <AboutPage/>
      <ContactForm/>
      
  

    
   
      
      
     
  

    </div>
  );
}
