
import Head from 'next/head';
import { Header } from '../components/Header';
import Homepage from '../components/Homepage';
import AboutPage from '../components/AboutPage';
import ServicePage from '../components/ServicePage';
import ContactForm from '../components/ContactForm';
import Footer from '../components/Footer';
import Slider from '../components/Slider';


export default function Home() {
  return (
    <div className="" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <div className="  overflow-hidden bg-cover bg-center bg-[url('/img/home-bg.png')]" >
      <Header />
   <Homepage/>

      </div>
      <ServicePage/>
     
      <AboutPage/>
      <ContactForm/>
      <Footer/>
      
  

    
   
      
      
     
  

    </div>
  );
}
